"""Local stand-in for the NCU weather chain, for testing while the real server
(140.115.54.87:8000) is down. Serves the SAME path + request shape as the real one
  POST /chain/resWeatherChain/stream   {"input": {"query": ..., "model": ...}}
and streams back the SAME LangServe SSE wire format
  event: data\r\n data: "<chunk>"\r\n \r\n  ...  event: end\r\n \r\n
so WeatherChainLLMService.extract_sse_text() is exercised exactly as in production.

The answer is generated by LOCAL qwen (Ollama) -- it is a plausible *mock* forecast,
NOT real weather data. Point WEATHER_CHAIN_URL back at NCU when it's up.

Run:  python -m scripts.mock_weather_chain        (serves :8077)
"""
from __future__ import annotations

import json

import httpx
import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse

# Local model that fabricates the demo answer (CPU-pinned -> GPU stays free for the
# avatar). Concise Traditional-Chinese weather persona.
OLLAMA = "http://localhost:11434/v1/chat/completions"
MODEL = "qwen2.5:3b-cpu"
SYSTEM = (
    "你是台灣的氣象播報助理。根據使用者的問題，用繁體中文、口語、簡短（最多兩句）"
    "回答天氣狀況，可包含溫度、降雨機率等。直接給答案，不要說你是 AI 或這是模擬。"
)

app = FastAPI()


def _sse(event: str, data: str = "") -> bytes:
    return f"event: {event}\r\ndata: {data}\r\n\r\n".encode("utf-8")


@app.post("/chain/resWeatherChain/stream")
async def stream(request: Request):
    body = await request.json()
    query = (body.get("input") or {}).get("query", "")
    print(f"[mock] query[{len(query)} chars] -> generating via {MODEL}")

    async def gen():
        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": query},
            ],
            "temperature": 0.5,
            "max_tokens": 120,
            "stream": True,
        }
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                async with client.stream("POST", OLLAMA, json=payload) as r:
                    r.raise_for_status()
                    async for line in r.aiter_lines():
                        s = line.strip()
                        if not s.startswith("data:"):
                            continue
                        chunk = s[5:].strip()
                        if chunk == "[DONE]":
                            break
                        try:
                            delta = json.loads(chunk)["choices"][0]["delta"].get("content")
                        except (json.JSONDecodeError, KeyError, IndexError):
                            continue
                        if delta:
                            # LangServe streams each piece as a JSON string after `data: `
                            yield _sse("data", json.dumps(delta, ensure_ascii=False))
        except Exception as e:  # noqa: BLE001
            print(f"[mock] generation error: {type(e).__name__}: {e}")
            yield _sse("data", json.dumps("抱歉，模擬天氣服務出錯了。", ensure_ascii=False))
        yield _sse("end")

    return StreamingResponse(gen(), media_type="text/event-stream")


if __name__ == "__main__":
    print("Mock weather chain on http://localhost:8077/chain/resWeatherChain/stream")
    uvicorn.run(app, host="0.0.0.0", port=8077, log_level="warning")
